# fly.toml app configuration file generated for bih-payments on 2023-05-30T00:36:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bih-payments"
primary_region = "lhr"

[http_service]
  internal_port = 6000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
